### ISSUE TITLE
Repository add-on repository.anontester uses old schema definition for the repository extension point

### ISSUE THREAD

**Issue by fexofenadine** [AnonTester/kodi-repo#3]
Lots of errors trying to access the repo, and check for available addon versions/updates:

ERROR <general>: Repository add-on repository.anontester uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.

And

ERROR <general>:Repository add-on repository.anontester does not have any directory and won't be able to update/serve addons! Plwase fox the addon.xml definition

These errors repeat many times in the log. This is happening in the latest Android x64 nightlies, I'm not sure how long its been happening. The subtitle plugins still search and return results correctly but cannot save the subs either, which may have the same cause but could be something in my setup.

I've tried reinstalling the repository zip file but it continues the same behaviour

**Comment by AnonTester** [comment]
sorry, never got a notification about this. I'm also not monitoring the nightlies and as you're probably aware, things change or break in nightlies without much notice. This appears to have been changed in the nightlies code on 23/Feb. 

I've adjusted my repository addon.xml file now. This should allow you to use the repo again in the nightlies. Please test and let me know either way.

For anything re the addons, please post in the forum or raise an issue in the respective addon github with full debug log via pastebin or paste.kodi.tv

**Comment by fexofenadine** [comment]
Hi mate sorry for the delay in testing - looks like it's working. Thanks a lot
